name: add_ssh_deploy_server.yml
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server (lokasbot)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          request_pty: true
          script_stop: true
          #password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          # script: whoami
          script: |
             become lokasbot sh -c "chmod +x actions/lokasbot/pull.sh; actions/lokasbot/pull.sh"
