name: add_ssh_deploy_server.yml
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to server (lokasbot)
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          request_pty: true
          script_stop: true
          #password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.KEY }}
          # script: whoami
          script: |
             become lokasbot sh -c "rm -rfd action_temp; git clone https://github.com/LokasWiki/actions.git action_temp; chmod +x action_temp/lokasbot/pull.sh; action_temp/lokasbot/pull.sh"
             become lokasbot2 sh -c "rm -rfd action_temp; git clone https://github.com/LokasWiki/actions.git action_temp; chmod +x action_temp/lokasbot2/pull.sh; action_temp/lokasbot2/pull.sh"
