name: add_ssh_deploy_server.yml
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to server (lokasbot)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          # password: ${{ secrets.PASSWORD }}
          key: ${{ secrets.SSHKEY }}
          # script: whoami
          script: |
            become lokasbot 
            cd $Home 
            actions/lokasbot/pull.sh
