name: Python Tests

on:
  push:
    branches: [ main, master ]
    paths:
      - 'tasks/sandbox/**'
      - 'tests/tasks/sandbox/**'
      - '.github/workflows/python-tests.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'tasks/sandbox/**'
      - 'tests/tasks/sandbox/**'
      - '.github/workflows/python-tests.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pywikibot
        pip install typing-extensions
        pip install coverage pytest pytest-cov
        
    - name: Run tests with coverage
      run: |
        cd code
        coverage run -m pytest tests/tasks/sandbox/test_*.py -v
        coverage report
        coverage xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./code/coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true 